version: '3'

services:
  mysqldb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
      # mysql_native_password is the default authentication plugin
      #used for an account when no authentication plugin is explicitly mentioned
    #ports:
    #  - "3306:3306"
    environment:
      MYSQL_DATABASE: ecomm
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mystorage:/var/lib/mysql

  monolithic_order:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password

  fallback:
    image: debian
    command: sleep 36000

volumes:
  mystorage:
