version: '3.4'

x-common-variables: &common-variables
  DATASOURCE_HOST: ${DB_HOST}
  DATASOURCE_USER: ${DB_USER}
  DATASOURCE_PASSWORD: ${DB_PASSWORD}
  DATASOURCE_NAME: ${DB_DATABASE}
  DATASOURCE_PORT: ${DB_PORT}

services:
  mysqldb:
    image: mysql:5.7
    command:
      --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mystorage:/var/lib/mysql

  usermanager:
    build:
      context: .
      dockerfile: usermanager/Dockerfile
    depends_on:
      - mysqldb
    ports:
      - "2222:2222"
    restart: always
    environment:
      <<: *common-variables

  productmanager:
    build:
      context: .
      dockerfile: productmanager/Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      - mysqldb
    restart: always
    environment:
      <<: *common-variables

  ordermanager:
    build:
      context: .
      dockerfile: ordermanager/Dockerfile
    ports:
      - "4444:4444"
    depends_on:
      - mysqldb
    restart: always
    environment:
      <<: *common-variables

volumes:
  mystorage: