version: '3.4'

x-common-variables: &common-variables
  DATASOURCE_HOST: ${DB_HOST}
  DATASOURCE_USER: ${DB_USER}
  DATASOURCE_PASSWORD: ${DB_PASSWORD}
  DATASOURCE_NAME: ${DB_DATABASE}
  DATASOURCE_PORT: ${DB_PORT}
  REGISTRATION_SERVER: ${REGISTRATION_SERVER_HOST}
  REGISTRATION_SERVER_PORT: ${REGISTRATION_SERVER_PORT}


services:
  mysqldb:
    image: mysql:5.7
    command:
      --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mystorage:/var/lib/mysql

  registrationserver:
    build:
      context: .
      dockerfile: registrationserver/Dockerfile
    ports:
      - "1111:1111"
    restart: always

  springgateway:
    build:
      context: .
      dockerfile: springgateway/Dockerfile
    ports:
      - "9999:9999"
    depends_on:
      - registrationserver
    restart: always
    environment:
      REGISTRATION_SERVER: ${REGISTRATION_SERVER_HOST}
      REGISTRATION_SERVER_PORT: ${REGISTRATION_SERVER_PORT}

  usermanager:
    build:
      context: .
      dockerfile: usermanager/Dockerfile
    depends_on:
      - mysqldb
      - registrationserver
    restart: always
    environment:
      <<: *common-variables

  productmanager:
    build:
      context: .
      dockerfile: productmanager/Dockerfile
    depends_on:
      - mysqldb
      - registrationserver
    restart: always
    environment:
      <<: *common-variables

  ordermanager:
    build:
      context: .
      dockerfile: ordermanager/Dockerfile
    depends_on:
      - mysqldb
      - registrationserver
    restart: always
    environment:
      <<: *common-variables

volumes:
  mystorage: